Portfolio website Desktop version
sylvester-wamaya/portfolio-website pull request #6
Opened 2023-04-06 21:07 UTC by sylvester-wamaya

- Add desktop styling version to the `nav` bar
- Add desktop styling version to the Home section.
- Add the desktop styling version to the works section.
- Add desktop styling version to the About me section.
- Add desktop styling version to the contact form section.
- Add desktop styling version to the `footer`.
- Add button interaction styling.

2023-04-06 22:01 UTC, amon-cofie requested changes
Hi @sylvester-wamaya , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! 💪 

<img src="https://media0.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif"/>

## Highlights

🚀 You have a descriptive pull request summary
🚀 You have a professional Readme file
🚀 You have good commit messages
🚀 You used GitHub flow properly
🚀 You have no linter errors

## Required Changes ♻️

- [ ] You have done awesome work on this project and your page looks almost like a clone of the figma template 👏 👍. However, this is your portfolio and in your works section you would want your user and hence your potential employer to be able to get a link to the project on GitHub 😉. I suggest in that light that you add the ```"see project"``` button and remove the dark background so that the project image can be seen when you hover on the projects in the works section. To put this in perspective, the first card in the figma template illustrates how the project card will look when it is hovered and the other cards illustrate how the projects will look on the page when not hovered. Check the screenshots below.

![image](https://user-images.githubusercontent.com/107795045/230500769-96641452-ecc9-41f6-8d6d-abae616cde2c.png)

- [ ] Your desktop version looks really great and you should make sure your mobile version also looks as good 😉 Your navigation menu shows on your mobile page in a way it should not but I'm sure this is an easy fix for you 👍 💪 . Please check the screenshot below: 

Your design: 
![image](https://user-images.githubusercontent.com/107795045/230501604-f2ae0a14-033e-4f04-9c8e-890e5cba3a32.png)

Figma design: 
![image](https://user-images.githubusercontent.com/107795045/230501783-338ade97-b67b-48ef-b695-38fd9a6b23d4.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 00:51 UTC, tresorsawasawa requested changes
# STATUS: REQUEST CHANGES :recycle::recycle: 

Hi @sylvester-wamaya 
Great work on making the changes requested by the previous reviewer  👏👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 00:51 UTC, tresorsawasawa commented on mobile.css
- [ ] As mentioned by the previous reviewer and for the project requirements, kindly make sure your navigation menu options are not visible in a mobile screen. To handle that, you should use media queries in your CSS file to make your desktop version look like the template you selected (Desktop: >=768px). In screen size < 768px only the Hamburger shoulb visible and the one >= 768px then your navigation options should visible and the Hamburger hidden. For a short remind about media queries, just refer this **[article](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)**. 
### Your Design in mobile size

![mob](https://user-images.githubusercontent.com/83042742/230518664-b4dad258-bf1b-4a1c-88ee-b4fae3fdb0a9.gif)

2023-04-07 11:46 UTC, NahnahAJ approved these changes
## Project Status: APPROVED :green_circle: 
Hi @sylvester-wamaya , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/d31w24psGYeekCZy/giphy.gif"/>

## Highlights
- Descriptive pull request summary :heavy_check_mark: 
- Professional Readme file :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- No linter errors :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-07 11:49 UTC, merged

2023-04-07 14:41 UTC, MasterLeiva reviewed
Great job on your portfolio design so far!
We kindly suggest you take a look into the following issues so that you can improve your website! 🙌🏼

_Take a look at the comments below_

2023-04-07 14:41 UTC, MasterLeiva commented on styles.css
> +  }
I suggest that the div element be styled using the background color attribute and giving a height to the div of 1px.

2023-04-07 14:41 UTC, MasterLeiva commented on styles.css
> +  }
I kindly suggest you turn the container of the buttons into a flex container so that you don't have hover issues.